services:
  - type: web
    name: robo-otimizador
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app --timeout 200"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
    plan: free

